### ISSUE TITLE
checklist of things desired for argo_map

### ISSUE THREAD

**Issue by dankelley** [dankelley/teaching_shiny#10]
* [x] add a way to get a line joining up the cycles for each float
* [x] add a way to track a given float, showing it's whole lifetime and ignoring other floats
* [x] respond to an `r` keystroke by restarting the view as it was when app launched
* [x] add a way to show the R code to get the view in the `argoFloats` package (thus, this app will be a sort of tutor for parts of the package)

**Comment by j-harbin** [comment]
Hi Dan,

I can't edit directly in your comment, but I suggest added a key stroke that brings you back to the default settings. I'm more specifically thinking about time here. I had been playing around on the app and then read one of your emails talking about the Indian Ocean at the default time, and I had to X out of the app, and reload to figure out what that was.

**Comment by dankelley** [comment]
Thanks, the `r` keystroke now works.  I propose to leave this open for a while.

**Comment by dankelley** [comment]
I'm closing this, because these issues have all been addressed.  There have been other cool new features, too.
